
class ClientPackets:
    CGetClasses, \
    CNewAccount, \
    CDelAccount, \
    CLogin,      \
    CAddChar,    \
    CDelChar,    \
    CUseChar,    \
    CSayMsg,     \
    CEmoteMsg,  \
    CBroadcastMsg, \
    CGlobalMsg,  \
    CAdminMsg, \
    CPlayerMsg,  \
    CPlayerMove, \
    CPlayerDir,  \
    CUseItem, \
    CAttack, \
    CUseStatPoint, \
    CPlayerInfoRequest, \
    CWarpMeTo,  \
    CWarpToMe,  \
    CWarpTo,    \
    CSetSprite, \
    CGetSprite, \
    CRequestNewMap, \
    CMapData,    \
    CNeedMap,    \
    CMapReport,  \
    CMapRespawn, \
    CMapGetItem, \
    CMapRespawn, \
    CKickPlayer, \
    CRequestEditMap, \
    CRequestEditItem, \
    CEditItem, \
    CSaveItem, \
    CRequestEditSpell, \
    CEditSpell, \
    CSaveSpell, \
    CSpells, \
    CRequestEditNpc, \
    CEditNpc, \
    CSaveNpc, \
    CDelete, \
    CSetAccess, \
    CGiveItem,  \
    CWhosOnline, \
    CSetMotd, \
    CQuit        \
    = range(49)


class ServerPackets:
    SAlertMsg,   \
    SAllChars,   \
    SLoginOK,    \
    SNewCharClasses, \
    SClassesData, \
    SInGame,     \
    SPlayerInv,  \
    SPlayerInvUpdate, \
    SPlayerWornEq, \
    SPlayerHP,   \
    SPlayerMP,   \
    SPlayerSP,   \
    SPlayerStats,\
    SPlayerLevel, \
    SPlayerData, \
    SPlayerMove, \
    SPlayerDir,  \
    SAttack,     \
    SNpcMove,    \
    SNpcDir,     \
    SNpcDead,    \
    SNpcEditor,  \
    SNpcAttack,  \
    SUpdateNpc,  \
    SEditNpc,    \
    SSpawnNpc,   \
    SCheckForMap,\
    SMapData,    \
    SMapItemData,\
    SMapNpcData, \
    SMapDone,    \
    SSayMsg,     \
    SGlobalMsg,  \
    SAdminMsg,   \
    SPlayerMsg,  \
    SMapMsg,     \
    SSpawnItem,  \
    SItemEditor, \
    SUpdateItem, \
    SSpellEditor, \
    SUpdateSpell, \
    SEditSpell, \
    SSpells, \
    SCastSpell, \
    SMapKey, \
    SEditMap, \
    SEditItem, \
    SMapList, \
    SLeft,       \
    SHighIndex   \
    = range(50)


class MessagePackets:
    MAccountCreated, \
    MHacker \
    = range(2)
